### ISSUE TITLE
Can you post a screenshot?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [zappfinger/OscCtcSound#1]
Hi there

Was looking at your GUI code.  I don't believe I'll be able to run it, but I'll try.

Just looking at the code, I see some unique stuff.  One, you're using a timeout value that's non-zero.  So many people don't know how to properly use the timeout; you clearly do.  You're also drawing rectangles and that means graphics!  That's exciting to see and would like to see what you're drawing or plotting.  

I'll try cloning and see what happens.

All you gotta do is copy and paste into this issue 👍

**Comment by zappfinger** [comment]
Shared some screenshots

**Comment by MikeTheWatchGuy** [comment]
Do you want the ability to turn off those numeric values?  Hmmm... I've not considered that some people may not want them visible.  I don't know yet how to turn them off.

With Qt, there are no numeric values shown, but it's easy to add your own by adding a Text Element that you update in the event loop to be the value of the slider.  I've done it several times and it works really well and it's easy to do.

This is the line of code you would need to add to update a Text Element with a slider value.
```python
window.Element('_NUMERIC OUTPUT_).Update(values['_SLIDER_'])
```
